project:
  type: website
  output-dir: _site

# Website config
website:
  title: Experiences of Learning to Code

  navbar:
    logo: metadata/favicon.png
    left:
      - text: Background
        href: background.qmd
      - text: Methods
      - text: Materials
        menu: 
          - research-materials/survey.md
          - research-materials/participant_info.md
          - research-materials/interview_guide.md
          - research-materials/for_interviewers.md
      - text: Results
      - text: Outputs
        menu:
          - text: Article
          - text: Presentation
          - text: Teaching Matters blog post
          - text: Methods paper
      - text: FAQ
        href: faq.md
    right:
      - icon: github
        href: "https://github.com/ExpLrnCode-2024/ExpLrnCode-2024.github.io"
        target: _blank
    #tools:

  favicon: metadata/favicon.png
  site-url: https://ExpLrnCode-2024.github.io
  repo-url: https://github.com/ExpLrnCode-2024/ExpLrnCode-2024.github.io
  #repo-actions: [source]

  page-footer:
    border: true
    background: light
    left: |
      [![](metadata/SoPA.png){fig-alt="SoPA logo" width=400px}](https://www.ph.ed.ac.uk/)
  
# Re-compute only when source changes
execute:
  freeze: auto

# Source shared metadata from these files
metadata-files:
  - metadata/format.yml
  - metadata/meta.yml
