project:
  type: website
  output-dir: _site

# Website config
website:
  title: Student Experiences and Perspectives on Learning to Code in 2024

  navbar:
    #logo: logo.png
    left:
      - href: about.qmd
        text: About
      - text: Guides
      - text: Resources
        menu:
          - resources/survey.md
          - resources/participant_info_consent.md
          - resources/interview_guide.md
          - resources/for_interviewers.md
      - text: FAQ
        href: faq.md
    right:
      - icon: github
        href: "https://github.com/seapolc-2024/seapolc-2024.github.io"
        target: _blank
      - text: |
          {{< iconify simple-icons:zenodo size=huge >}}
        aria-label: Zenodo
        href: "https://doi.org/10.5281/zenodo.xxxxxxxx"
        target: _blank

  #favicon: /logos/biodt_circle.png
  site-url: https://seapolc-2024.github.io
  repo-url: https://github.com/seapolc-2024/seapolc-2024.github.io
  
# Re-compute only when source changes
execute:
  freeze: auto

# Source shared metadata from these files
metadata-files:
  - metadata/format.yml
  - metadata/meta.yml
